POST {{url}}/auth/signup
Content-Type: application/json

{
  "login": "user6",
  "password": "user6",
  "email": "somemailjhgo@mail.com",
  "name": "hello",
  "surname": "there",
  "groupId": 1
}

###

POST {{url}}/auth/signin
Content-Type: application/json

{
  "login": "admin",
  "password": "adminpass"
}

###

POST {{url}}/auth/signin
Content-Type: application/json

{
  "login": "worker1",
  "password": "password1"
}

###

GET localhost:8080/users/admin
Accept: application/json
Authorization: {{admin_token}}

{
}
###

###

GET localhost:8080/optimizationProcess/run/152
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImxvZ2luIjoiYWRtaW4iLCJleHAiOjE3MTc0MjAzMzN9.UMfwe38z36rWX30bISO1kEuJ0nSMr0jqQ46iGxp7xL4

{
}
###

GET localhost:8080/optimizationProcess/run/
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImxvZ2luIjoiYWRtaW4iLCJleHAiOjE3MTc0MDcwMzJ9.hcbPRL2TtjeE9BECBZdSJgcnFWyMxy5-Jbn-RObvddk

{
}


###

PUT {{url}}//users
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyNSIsImxvZ2luIjoidXNlcjUiLCJleHAiOjE3MTU2MzYxNTl9.DK10GOvyvr5Mz7r_-P1jS7e0IMNTL1AGXhx_p_c8OB4

{
  "login": "user56",
  "email": "hol3lo@mail.com",
  "name": "Jan",
  "surname": "Kowalski",
  "groupId": 2
}

###

DELETE {{url}}/users/worker1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImxvZ2luIjoiYWRtaW4iLCJleHAiOjE3MTYxNzAzMjZ9.iZO1xSGtLaVpfLsyZo6p-vIELGNsGHzv96B9UazZ3_U
