POST {{url}}/auth/signup
Content-Type: application/json

{
  "login": "user6",
  "password": "user6",
  "email": "somemailjhgo@mail.com",
  "name": "hello",
  "surname": "there",
  "groupId": 1
}

###

POST {{url}}/auth/signin
Content-Type: application/json

{
  "login": "admin",
  "password": "adminpass"
}

###

GET {{url}}/users/worker1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImxvZ2luIjoiYWRtaW4iLCJleHAiOjE3MTYxNzE4Mjl9.Lcgrdd3rcQJMrja7_6tYkQwQgSnCqyNDJIyy7NOc0-k

{
}
###

PUT {{url}}//users
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyNSIsImxvZ2luIjoidXNlcjUiLCJleHAiOjE3MTU2MzYxNTl9.DK10GOvyvr5Mz7r_-P1jS7e0IMNTL1AGXhx_p_c8OB4

{
  "login": "user56",
  "email": "hol3lo@mail.com",
  "name": "Jan",
  "surname": "Kowalski",
  "groupId": 2
}

###

DELETE {{url}}/users/worker1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImxvZ2luIjoiYWRtaW4iLCJleHAiOjE3MTYxNzAzMjZ9.iZO1xSGtLaVpfLsyZo6p-vIELGNsGHzv96B9UazZ3_U
